services:
  ws:
    image: ethnexus/smnrp:2.5.1
    volumes:
      - "web_root:/web_root:z"
      - ./api/static:/vol/web/static:z
      - ./api/media:/vol/web/media:z
        #- /etc/pki/tls/certs/DCcerts2025/ldm.nexus.ethz.ch.chain.crt.pem:/etc/letsencrypt/live/ldm.nexus.ethz.ch/fullchain.pem:ro
      - /etc/pki/tls/certs/ldm.nexus.ethz.ch.pem:/etc/letsencrypt/live/ldm.nexus.ethz.ch/fullchain.pem:ro
        #- /etc/pki/tls/private/key2025/ldm.nexus.ethz.ch.privkey.pem:/etc/letsencrypt/live/ldm.nexus.ethz.ch/privkey.pem:ro
      - /etc/pki/tls/private/ldm.nexus.ethz.ch.key:/etc/letsencrypt/live/ldm.nexus.ethz.ch/privkey.pem:ro

    ports:
      - "8081:80"
      - "4431:443"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - api
      - db
  api:
    build:
      args:
        DEPENDENCIES: prod
    volumes:
      - /lab_shared_drive:/data
  ui:
    command:
      - /bin/sh
      - -c
      - |
        set -e
        mkdir -p /app/dist
        rm -rf /app/dist/*
        pnpm install --frozen-lockfile
        pnpm run build
        cp -a /app/.output/public/. /app/dist/
        rm -rf /app/.output
#    command: >
#      bash -c "\
#        yarn install
#        rm -rf /app/dist/*
#        yarn run build
#        mv /app/dist/spa/* /app/dist/.
#        rm -rf /app/dist/spa
#      "
