version: "3"

services:
  ui:
    ports:
      # We should use the same port internally and externally, otherwise the dev tools support
      # of the browser is for almost nothing
      - "8090:8090"
    command:
      - /bin/sh
      - -c
      - |
        yarn
        yarn dev --host 0.0.0.0 --port 8090
    # command: bash -c 'while true; do sleep 5; done'
    restart: unless-stopped
    depends_on:
      - api
  api:
    environment:
      - DJANGO_DEBUG=True
    ports:
      - "5090:5000"
      # - "8888:8888"
  db:
    ports:
      - "54390:5432"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

