version: "3"
volumes:
  pg_data:
  web_root:
  smnrp-data:
  static-data:
  smnrp_live:

services:
  ui:
    command: >
      bash -c "\
        yarn install
        yarn run build
      "
  api:
    environment:
          - DB_HOST=db
          - DB_NAME=${POSTGRES_DB}
          - DB_USER=${POSTGRES_USER}
          - DB_PASS=${POSTGRES_PASSWORD}
          - SECRET_KEY=${DJANGO_SECRET_KEY}
          - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
          - DEV=False

  ws:
    image: ethnexus/smnrp
    volumes:
      - "web_root:/web_root:ro"
      - ./api/static:/vol/web/static:z
      - ./api/media:/vol/web/media:z
      - smnrp-data:/etc/letsencrypt
      - /etc/pki/tls/certs/DCcerts2023:/etc/letsencrypt/live/ldm.nexus.ethz.ch/fullchain.pem:ro
      - /etc/pki/tls/private/key2023:/etc/letsencrypt/live/ldm.nexus.ethz.ch/privatekey.pem:ro

    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - api
      - db
      - ui
