version: "3"
volumes:
  pg_data:
  api_notebooks:
  api_backups:
  api_media:

services:
  api:
    platform: linux/amd64
    image: lab_management-api:local
    hostname: api
    restart: unless-stopped
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - api_notebooks:/notebooks
      - api_backups:/vol/backups
      - api_media:/vol/web/media:z
    env_file: .env
    environment:
      - GIT_VERSION=${GIT_VERSION}
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_LASTCOMMITDATE=${GIT_LASTCOMMITDATE}
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: lab_management-db:local
    hostname: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
