
services:
#  ui:
#    platform: linux/arm64/v8
#    ports:
#      - "8090:8090"
#    command:
#      - /bin/sh
#      - -c
#      - |
#        yarn
#        yarn dev --host 0.0.0.0 --port 8090
#    restart: unless-stopped
#    depends_on:
#      - api

  ui:
    restart: unless-stopped
    depends_on:
      - api
    platform: linux/arm64/v8
    ports:
      - "8091:3000"
    command:
      - /bin/sh
      - -c
      - |
        corepack enable
        pnpm install --no-frozen-lockfile
        pnpm dev --host 0.0.0.0 --port 3000

  api:
    build:
      args:
        DEPENDENCIES: dev
    environment:
      - DJANGO_DEBUG=True
    ports:
      - "5090:5000"
      - "8890:8888"

  db:
    ports:
      - "54390:5432"
