version: "3"
services:
  ws:
    image: ethnexus/smnrp:1.1.1
    volumes:
      - "web_root:/web_root:z"
      - ./api/static:/vol/web/static:z
      - ./api/media:/vol/web/media:z
      - /etc/pki/tls/certs/DCcerts2024/ldm.nexus.ethz.ch.chain.crt.pem:/etc/letsencrypt/live/ldm.nexus.ethz.ch/fullchain.pem:ro
      - /etc/pki/tls/private/key2024/ldm.nexus.ethz.ch.privkey.pem:/etc/letsencrypt/live/ldm.nexus.ethz.ch/privkey.pem:ro

    ports:
      - "8081:80"
      - "4431:443"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - api
      - db
  api:
    volumes:
      - /lab_shared_drive:/data
  ui:
    command: >
      bash -c "\
        yarn install
        rm -rf /app/dist/*
        yarn run build
        mv /app/dist/spa/* /app/dist/.
        rm -rf /app/dist/spa
      "
