version: "3"
volumes:
  pg_data:
  web_root:
services:
  ui:
    build:
      context: ui
    volumes:
      - ./ui/app:/app
      - "web_root:/app/dist:z"
    hostname: ui
    restart: "no"
    env_file: .env

  api:
    build:
      context: api
      args:
        ENABLE_JUPYTER: ${ENABLE_JUPYTER}
        ENABLE_R: ${ENABLE_R}
    hostname: api
    restart: unless-stopped
    entrypoint: sh -c '/app/entrypoint.sh'
    volumes:
      - ./api/app:/app
      - ./api/notebooks:/notebooks
      # - ./api/app/notebook/startup:/root/.ipython/profile_default/startup
      # - ./api/app/notebook/nbextensions/printview:/root/.local/share/jupyter/nbextensions/printview
      - ./api/backups:/vol/backups
      - ./api/static:/vol/web/static:z
      - ./api/media:/vol/web/media:z
      - ./data:/data
      - ./README.md:/app/README.md
      - ./.git:/app/docs/.git
      # - ./api/notebooks:/data/notebooks
      - ./conf/jupyter:/root/.jupyter
      - ./conf/ipython:/root/.ipython
    env_file: .env
    environment:
      - GIT_VERSION=${GIT_VERSION}
      - GIT_BRANCH=${GIT_BRANCH}
      - GIT_LASTCOMMITDATE=${GIT_LASTCOMMITDATE}
    depends_on:
      - db
  db:
    build:
      context: db
    hostname: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
