version: "3"
services:
  ws:
    platform: linux/amd64
    image: lab_management-ws:local
    volumes:
      - "api_media:/vol/web/media:z"
        #- /etc/pki/tls/certs/DCcerts2025/ldm.nexus.ethz.ch.chain.crt.pem:/etc/letsencrypt/live/ldm.nexus.ethz.ch/fullchain.pem:ro
      - /etc/pki/tls/certs/ldm.nexus.ethz.ch.pem:/etc/letsencrypt/live/ldm.nexus.ethz.ch/fullchain.pem:ro
        #- /etc/pki/tls/private/key2025/ldm.nexus.ethz.ch.privkey.pem:/etc/letsencrypt/live/ldm.nexus.ethz.ch/privkey.pem:ro
      - /etc/pki/tls/private/ldm.nexus.ethz.ch.key:/etc/letsencrypt/live/ldm.nexus.ethz.ch/privkey.pem:ro

    ports:
      - "8081:80"
      - "4431:443"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - api
      - db
  api:
    image: lab_management-api:local
    volumes:
      - /lab_shared_drive:/data
  db:
    image: lab_management-db:local
