# Generated by Django 4.2.3 on 2024-03-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compoundlib', '0015_alter_compound_structure'),
        ('core', '0010_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('empty_well', 'Empty Well')], max_length=100)),
                ('status', models.CharField(default='open', max_length=100)),
                ('details', models.JSONField(blank=True, null=True)),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compoundlib.compoundlibrary')),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.well')),
            ],
        ),
    ]
