# Generated by Django 4.2.3 on 2024-03-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='well_hr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
