# Generated by Django 4.2.3 on 2026-09-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_problem_well_hr"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Problem",
        ),
    ]
