site_name: Lab Data Management Documentation
docs_dir: docs
site_dir: site
nav:
  - "Getting started": getting_started.md
  - "Command line tools": index.md
  - Changelog: CHANGELOG.md
theme: readthedocs

extra_css:
  - css/default.css