# Generated by Django 4.2.3 on 2026-04-01 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_plate_use_as_template_to_select'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name if applicable, e.g. Costar, Cellstar, Twin.tec.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Compatible device type, e.g. LiHa, MCA96, MCA384, Hand pipette.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Device type',
                'verbose_name_plural': 'Device types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, help_text='Current stock quantity in the selected stock unit. Can be fractional for open boxes, e.g. 0.8, 1.25, 2.041667.', max_digits=12)),
                ('minimum_quantity', models.DecimalField(decimal_places=6, default=0, help_text="Minimum desired quantity in the same unit as 'quantity'. Used to derive low-stock status.", max_digits=12)),
                ('lot_number', models.CharField(blank=True, help_text='Lot / batch number for this specific stock entry.', max_length=255, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date for this specific lot / batch if applicable.', null=True)),
                ('is_favorite', models.BooleanField(default=False, help_text='Optional flag if the lab wants to mark favorite / pinned stock items.')),
                ('notes', models.TextField(blank=True, help_text="Free-text stock notes, e.g. '1 open box', 'outside box', 'all open', 'very old', 'single reservoirs'.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this stock entry was created in the system.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this stock entry was last updated.')),
            ],
            options={
                'verbose_name': 'Inventory stock',
                'verbose_name_plural': 'Inventory stock',
                'ordering': ['material__product_name', 'sector__room__name', 'sector__name'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='General material category, e.g. tip box, plate, tube, reagent, spare part.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Item type',
                'verbose_name_plural': 'Item types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Manufacturer name, e.g. Tecan, Eppendorf, Corning.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Reusable attribute, e.g. sterile, filtered, low retention, wide bore.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Material attribute',
                'verbose_name_plural': 'Material attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Catalog product name copied from vendor/manufacturer if possible.', max_length=255)),
                ('manufacturer_catalog_number', models.CharField(blank=True, db_index=True, help_text='Manufacturer catalog number, e.g. 30038616, 3815, 710180.', max_length=255, null=True)),
                ('vendor_catalog_number', models.CharField(blank=True, db_index=True, help_text='Vendor catalog number. May be identical to manufacturer catalog number.', max_length=255, null=True)),
                ('capacity_value', models.DecimalField(blank=True, decimal_places=3, help_text='Capacity / size of one single piece, e.g. 200, 50, 1.5, 75.', max_digits=12, null=True)),
                ('capacity_unit', models.CharField(blank=True, help_text='Capacity unit, e.g. ul, ml, L, mm, um, cm2, gal.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional free-text description for extra metadata not captured elsewhere.', null=True)),
                ('default_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Optional default/reference cost for one order unit or stock unit.', max_digits=12, null=True)),
                ('lifetime_days', models.PositiveIntegerField(blank=True, help_text='Optional default lifetime in days, mainly useful for equipment or reusable items.', null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Optional serial number. Usually relevant only for devices/accessories, not consumables.', max_length=255, null=True)),
                ('order_number', models.CharField(blank=True, help_text='Optional internal order reference.', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft flag to hide discontinued materials without deleting history.')),
                ('attributes', models.ManyToManyField(blank=True, help_text='Flexible repeatable attributes like sterile, filtered, pure, wide bore.', related_name='materials', to='inventory.materialattribute')),
                ('brand', models.ForeignKey(blank=True, help_text='Optional brand, e.g. Costar, Cellstar, Twin.tec.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.brand')),
                ('device_type', models.ForeignKey(blank=True, help_text='Compatible device if applicable, e.g. LiHa, MCA96, MCA384, Hand pipette.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.devicetype')),
                ('item_type', models.ForeignKey(blank=True, help_text='General item category, e.g. tip box, plate, tube, reagent, spare part.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.itemtype')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Manufacturer of the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.manufacturer')),
            ],
            options={
                'verbose_name': 'Material master',
                'verbose_name_plural': 'Material master records',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base_unit', models.BooleanField(default=False, help_text='Marks the smallest logical unit for this material, e.g. tip, glove, tube, piece.')),
                ('is_stock_unit', models.BooleanField(default=False, help_text='Marks the unit usually used in inventory stock records, e.g. box, bag, plate, piece.')),
                ('is_order_unit', models.BooleanField(default=False, help_text='Marks the unit usually used when ordering from suppliers.')),
                ('base_units_per_unit', models.DecimalField(decimal_places=6, default=1, help_text='How many base units are contained in one of this unit. Examples: tip=1, tip box=96, glove box=100, carton=960.', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text="Optional explanation for unusual packaging from our original excel, e.g. '24 racks in 2er blister', 'single reservoirs', '1 open box'.", null=True)),
                ('material', models.ForeignKey(help_text='Material to which this unit definition belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.materialmaster')),
            ],
            options={
                'verbose_name': 'Material unit',
                'verbose_name_plural': 'Material units',
                'ordering': ['material__product_name', 'unit__name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room name, e.g. C75, C41, C21.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Inventory unit, e.g. piece, box, bag, rack, plate, bottle.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Unit of measure',
                'verbose_name_plural': 'Units of measure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vendor / supplier name, e.g. Witec, D-BIOL shop, Huberlab.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sector / shelf label inside the room.', max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='inventory.room')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['room__name', 'name'],
                'unique_together': {('room', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, help_text='Ordered quantity in the selected order unit.', max_digits=12)),
                ('order_date', models.DateTimeField(help_text='Date/time when the order was placed or recorded.')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('tentative', 'Tentative'), ('product_arrived', 'Product arrived')], default='ordered', help_text='Current order status.', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Free-text notes about the order.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(help_text='Material being ordered.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.materialmaster')),
                ('order_unit', models.ForeignKey(help_text='Unit in which the order was placed, e.g. box, carton, piece.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.materialunit')),
                ('project', models.ForeignKey(blank=True, help_text='Optional project to which this order belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_orders', to='core.project')),
                ('who_ordered', models.ForeignKey(blank=True, help_text='User who placed the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=6, help_text='Consumed quantity in the selected usage unit.', max_digits=12)),
                ('used_at', models.DateTimeField(auto_now_add=True, help_text='When this material usage was recorded.')),
                ('notes', models.TextField(blank=True, help_text='Optional free-text notes about the usage.', null=True)),
                ('experiment', models.ForeignKey(blank=True, help_text='Optional experiment within the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usages', to='core.experiment')),
                ('inventory_stock', models.ForeignKey(help_text='Stock entry from which the material was consumed.', on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='inventory.inventorystock')),
                ('project', models.ForeignKey(help_text='Project to which the material usage belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='core.project')),
                ('usage_unit', models.ForeignKey(help_text='Unit used for this consumption entry, e.g. piece, tip, box, plate.', on_delete=django.db.models.deletion.PROTECT, related_name='usage_entries', to='inventory.materialunit')),
            ],
            options={
                'verbose_name': 'Material usage',
                'verbose_name_plural': 'Material usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddField(
            model_name='materialunit',
            name='unit',
            field=models.ForeignKey(help_text='Unit name, e.g. piece, box, bag, rack, plate, bottle.', on_delete=django.db.models.deletion.PROTECT, related_name='material_units', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='materialmaster',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor / supplier from whom the item is ordered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='material',
            field=models.ForeignKey(help_text='Material master record for this stock item.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.materialmaster'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='sector',
            field=models.ForeignKey(help_text='Physical storage location of this stock entry.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.sector'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='stock_unit',
            field=models.ForeignKey(help_text='Unit in which this stock entry is counted, e.g. box, piece, bag.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='inventory.materialunit'),
        ),
        migrations.AlterUniqueTogether(
            name='materialunit',
            unique_together={('material', 'unit')},
        ),
    ]
