# Generated by Django 4.2.3 on 2026-04-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Optional flag if we want to mark favorite / pinned stock items.'),
        ),
    ]
