# Generated by Django 4.2.3 on 2026-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorystock_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystock',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Optional flag if we want to hide archived stock items.'),
        ),
    ]
