# Generated by Django 4.2.3 on 2026-07-01 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_inventorystock_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStockTablePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_key', models.CharField(choices=[('inventory_stock', 'Inventory stock')], default='inventory_stock', help_text='Identifies which table this preference record belongs to.', max_length=100)),
                ('preset', models.CharField(default='all', help_text='Saved stock preset, e.g. all, favorite, low_stock, or expired.', max_length=50)),
                ('sorting', models.JSONField(blank=True, default=list, help_text='Saved TanStack sorting state for the stock table.')),
                ('column_filters', models.JSONField(blank=True, default=list, help_text='Saved TanStack column filter state for the stock table.')),
                ('column_order', models.JSONField(blank=True, default=list, help_text='Saved visible column order for the stock table.')),
                ('column_visibility', models.JSONField(blank=True, default=dict, help_text='Saved visible/hidden column state keyed by column id.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this preference record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this preference record was last updated.')),
                ('user', models.ForeignKey(help_text='Authenticated user who owns this saved table state.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_table_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory stock table preference',
                'verbose_name_plural': 'Inventory stock table preferences',
                'ordering': ['user_id', 'table_key'],
                'unique_together': {('user', 'table_key')},
            },
        ),
    ]
