# Generated by Django 4.2.3 on 2026-07-06 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0018_alter_plate_barcode"),
        ("inventory", "0007_inventorystock_source_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryChangeRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "performed_action",
                    models.CharField(
                        choices=[
                            ("stock_created", "Stock created"),
                            ("stock_updated", "Stock updated"),
                            ("stock_deleted", "Stock deleted"),
                            ("stock_archived", "Stock archived"),
                            ("stock_restored", "Stock restored"),
                            ("stock_favorited", "Stock favorited"),
                            ("stock_unfavorited", "Stock unfavorited"),
                            ("order_created", "Order created"),
                            ("order_updated", "Order updated"),
                            ("order_deleted", "Order deleted"),
                            ("usage_created", "Usage created"),
                            ("usage_updated", "Usage updated"),
                            ("usage_deleted", "Usage deleted"),
                        ],
                        help_text="Type of inventory action that was performed.",
                        max_length=100,
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the action was recorded.",
                    ),
                ),
                (
                    "quantity_delta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text='Optional quantity change for the action. Example: {"quantity_delta": "-1.000000"} for a checkout.',
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional free-text explanation for the action.",
                        null=True,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional related experiment for the recorded action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_change_records",
                        to="core.experiment",
                    ),
                ),
                (
                    "inventory_stock",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related stock row if the action affected stock.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_records",
                        to="inventory.inventorystock",
                    ),
                ),
                (
                    "material_usage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related usage row if the action affected a material usage entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_records",
                        to="inventory.materialusage",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related order row if the action affected an order.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_records",
                        to="inventory.order",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user who performed the action if available.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_change_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional related project for the recorded action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_change_records",
                        to="core.project",
                    ),
                ),
                (
                    "quantity_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional unit used with quantity_delta.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_change_records",
                        to="inventory.materialunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory change record",
                "verbose_name_plural": "Inventory change records",
                "ordering": ["-performed_at", "-id"],
            },
        ),
    ]
