# Generated by Django 4.2.3 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_inventorychangerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorystock",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this stock entry was most recently archived. Cleared when the entry is restored.",
                null=True,
            ),
        ),
    ]
