# Generated by Django 4.2.3 on 2026-08-26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0009_inventorystock_archived_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorystock",
            name="is_favorite",
        ),
        migrations.AddField(
            model_name="inventorystock",
            name="favorite_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who marked this stock entry as a favorite.",
                related_name="favorite_inventory_stocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
