# Generated by Django 4.1.4 on 2023-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platetemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platetemplate',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
