# Generated by Django 4.1.4 on 2023-01-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platetemplate', '0002_alter_platetemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platetemplatecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='platetemplate',
            unique_together={('name', 'category')},
        ),
    ]
