# Generated by Django 4.1.4 on 2023-01-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platetemplate', '0003_alter_platetemplatecategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platetemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='platetemplate.platetemplatecategory'),
        ),
    ]
