# Generated by Django 4.1.3 on 2022-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('structure', models.TextField()),
                ('smile', models.TextField()),
                ('data', models.JSONField()),
            ],
        ),
    ]
