# Generated by Django 4.1.3 on 2022-12-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='identifier',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
