# Generated by Django 4.1.3 on 2022-12-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0002_alter_compound_data_alter_compound_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='compoundlib.compoundlibrary'),
        ),
    ]
