# Generated by Django 4.1.3 on 2022-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0003_compoundlibrary_compound_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundlibrary',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compoundlibrary',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
