# Generated by Django 4.1.3 on 2022-12-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0004_compoundlibrary_file_name_alter_compoundlibrary_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compoundlibrary',
            options={'verbose_name_plural': 'compound libraries'},
        ),
        migrations.AlterField(
            model_name='compoundlibrary',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='compound library'),
        ),
    ]
