# Generated by Django 4.1.4 on 2022-12-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0005_alter_compoundlibrary_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='structure',
            new_name='name',
        ),
    ]
