# Generated by Django 4.1.4 on 2022-12-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0006_rename_structure_compound_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='smile',
            new_name='structure',
        ),
    ]
