# Generated by Django 4.1.7 on 2023-03-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0007_rename_smile_compound_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compoundlibrary',
            options={'ordering': ('name',), 'verbose_name_plural': 'compound libraries'},
        ),
    ]
