# Generated by Django 4.2.1 on 2023-06-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0009_alter_compound_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundlibrary',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
