# Generated by Django 4.2.3 on 2023-07-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0010_alter_compoundlibrary_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compounds', to='compoundlib.compoundlibrary'),
        ),
    ]
