# Generated by Django 4.2.3 on 2023-07-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0011_alter_compound_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compounds', to='compoundlib.compoundlibrary'),
        ),
    ]
