# Generated by Django 4.2.3 on 2024-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0012_alter_compound_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='identifier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
