# Generated by Django 4.2.3 on 2024-03-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0013_alter_compound_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='library',
        ),
    ]
