# Generated by Django 4.1.3 on 2022-11-29 15:12

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', core.models.AutoDateTimeField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', core.models.AutoDateTimeField()),
                ('barcode', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlateDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cols', models.PositiveIntegerField()),
                ('rows', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', core.models.AutoDateTimeField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', core.models.AutoDateTimeField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', core.models.AutoDateTimeField()),
                ('position', models.PositiveIntegerField()),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WellRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('from_well', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_wells', to='core.well')),
                ('to_well', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='from_wells', to='core.well')),
            ],
        ),
        migrations.AddField(
            model_name='well',
            name='from_well',
            field=models.ManyToManyField(through='core.WellRelation', to='core.well'),
        ),
        migrations.AddField(
            model_name='well',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.plate'),
        ),
        migrations.AddField(
            model_name='well',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sample'),
        ),
        migrations.AddField(
            model_name='plate',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.platedimension'),
        ),
        migrations.AddField(
            model_name='plate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.project'),
        ),
    ]
