# Generated by Django 4.1.3 on 2022-11-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='barcode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.project'),
        ),
        migrations.AlterField(
            model_name='well',
            name='drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='core.drug'),
        ),
        migrations.AlterField(
            model_name='well',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='wells', to='core.plate'),
        ),
        migrations.AlterField(
            model_name='well',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='core.sample'),
        ),
        migrations.AlterUniqueTogether(
            name='well',
            unique_together={('plate', 'position')},
        ),
    ]
