# Generated by Django 4.1.7 on 2023-03-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
