# Generated by Django 4.1.3 on 2022-11-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_plate_barcode_alter_plate_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
