# Generated by Django 4.1.7 on 2023-03-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_well_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementfeature',
            name='abbrev',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
