# Generated by Django 4.1.7 on 2023-03-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_measurementfeature_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementfeature',
            name='abbrev',
            field=models.CharField(default='TST', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
