# Generated by Django 4.1.3 on 2022-12-01 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_well_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platedimension',
            name='cols',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='platedimension',
            name='rows',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
