# Generated by Django 4.1.3 on 2022-12-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0002_alter_compound_data_alter_compound_identifier'),
        ('core', '0004_alter_platedimension_cols_alter_platedimension_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='data',
        ),
        migrations.RemoveField(
            model_name='well',
            name='drug',
        ),
        migrations.AddField(
            model_name='well',
            name='compound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wells', to='compoundlib.compound'),
        ),
        migrations.AlterField(
            model_name='well',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wells', to='core.sample'),
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
    ]
