# Generated by Django 4.2.3 on 2023-07-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plate_is_control_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='core.project'),
        ),
    ]
