# Generated by Django 4.1.3 on 2022-12-02 08:36

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0003_compoundlibrary_compound_library'),
        ('core', '0006_well_amount_alter_wellrelation_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', core.models.AutoDateTimeField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plate',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='compoundlib.compoundlibrary'),
        ),
    ]
