# Generated by Django 4.2.3 on 2023-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_plate_check_only_library_or_experiment_or_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='is_invalid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
