# Generated by Django 4.1.3 on 2022-12-02 12:16

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_location_plate_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='modified_at',
            field=core.basemodels.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='plate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='plate',
            name='modified_at',
            field=core.basemodels.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_at',
            field=core.basemodels.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='modified_at',
            field=core.basemodels.AutoDateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='well',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='well',
            name='modified_at',
            field=core.basemodels.AutoDateTimeField(editable=False),
        ),
    ]
