# Generated by Django 4.2.3 on 2024-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_measurement_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellwithdrawal',
            name='current_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wellwithdrawal',
            name='current_dmso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
