# Generated by Django 4.1.3 on 2022-12-02 12:59

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_location_created_at_alter_location_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', core.models.AutoDateTimeField(editable=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('abbrev', models.CharField(max_length=4, null=True)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='well',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.measurement'),
        ),
    ]
