# Generated by Django 4.1.3 on 2022-12-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_measurement_well_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='measurement',
        ),
        migrations.AddField(
            model_name='well',
            name='measurements',
            field=models.ManyToManyField(related_name='wells', to='core.measurement'),
        ),
    ]
