# Generated by Django 4.1.7 on 2023-03-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_measurement_created_at_measurementassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementassignment',
            name='measurement_timestamp',
        ),
    ]
