# Generated by Django 4.2.3 on 2024-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
