# Generated by Django 4.1.3 on 2022-12-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0005_alter_compoundlibrary_options_and_more'),
        ('core', '0010_remove_well_measurement_well_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='abbrev',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='measurement'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='compoundlib.compoundlibrary'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.project'),
        ),
        migrations.AlterField(
            model_name='platedimension',
            name='name',
            field=models.CharField(max_length=50, verbose_name='plate dimension'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=50, verbose_name='sample'),
        ),
        migrations.AlterField(
            model_name='well',
            name='compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wells', to='compoundlib.compound'),
        ),
        migrations.AlterField(
            model_name='well',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wells', to='core.sample'),
        ),
    ]
