# Generated by Django 4.1.7 on 2023-03-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_measurementassignment_measurement_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementassignment',
            name='measurement',
        ),
    ]
