# Generated by Django 4.1.3 on 2022-12-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_location_name_alter_measurement_abbrev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='measurements',
        ),
        migrations.AddField(
            model_name='measurement',
            name='well',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='measurements', to='core.well'),
            preserve_default=False,
        ),
    ]
