# Generated by Django 4.2.3 on 2024-06-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_plate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_plate_barcode', models.TextField()),
                ('label', models.TextField()),
                ('replicate', models.TextField()),
                ('measurement_time', models.DateTimeField()),
                ('cell_type', models.TextField()),
                ('condition', models.TextField()),
                ('plate_barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
            ],
        ),
    ]
