# Generated by Django 4.1.3 on 2022-12-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_well_measurements_measurement_well'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='well',
            options={'ordering': ('position',)},
        ),
    ]
