# Generated by Django 4.2.3 on 2024-06-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_plateinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plateinfo',
            old_name='plate_barcode',
            new_name='plate',
        ),
    ]
