# Generated by Django 4.1.7 on 2023-03-20 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_measurementassignment_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='measurementassignment',
            name='metadata',
        ),
        migrations.AddField(
            model_name='measurementmetadata',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_metadata', to='core.measurement'),
        ),
        migrations.AddField(
            model_name='measurementmetadata',
            name='measurement_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_metadata', to='core.measurementassignment'),
        ),
    ]
