# Generated by Django 4.1.7 on 2023-03-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_measurement_meta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementmetadata',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='measurementmetadata',
            name='measurement_assignment',
        ),
        migrations.AddField(
            model_name='measurement',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='measurements', to='core.measurementmetadata'),
        ),
        migrations.AddField(
            model_name='measurementassignment',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.measurementmetadata'),
        ),
    ]
