# Generated by Django 4.1.3 on 2022-12-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_well_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='well',
            options={},
        ),
    ]
