# Generated by Django 4.1.3 on 2022-12-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0005_alter_compoundlibrary_options_and_more'),
        ('core', '0014_alter_well_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plates', to='compoundlib.compoundlibrary'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plates', to='core.project'),
        ),
    ]
