# Generated by Django 4.1.7 on 2023-03-20 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_measurementmetadata_measurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='measurementassignment',
            name='metadata',
        ),
        migrations.AddField(
            model_name='measurementassignment',
            name='measurement_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.DeleteModel(
            name='MeasurementMetadata',
        ),
    ]
