# Generated by Django 4.1.7 on 2023-03-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_measurement_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='measurement_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.measurementassignment'),
        ),
    ]
