# Generated by Django 4.1.3 on 2022-12-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_plate_library_alter_plate_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='barcode',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
