# Generated by Django 4.1.7 on 2023-03-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_measurement_measurement_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='harvest_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
