# Generated by Django 4.2.3 on 2024-06-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_plateinfo_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='use_as_template_to_select',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
