# Generated by Django 4.1.7 on 2023-03-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_project_harvest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('harvest_id', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_project_mappings', to='core.project')),
            ],
        ),
    ]
