# Generated by Django 4.2.3 on 2026-05-29 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_plate_use_as_template_to_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='barcode',
            field=models.CharField(db_index=True, max_length=300, unique=True, validators=[django.core.validators.RegexValidator('[^\\s]+', 'Plate barcode must not contain strings!')]),
        ),
    ]
