# Generated by Django 4.1.7 on 2023-03-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_harvestprojectmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HarvestProjectMapping',
        ),
    ]
