# Generated by Django 4.2.3 on 2026-09-13 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_plate_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threshold",
            name="amount",
            field=models.FloatField(
                default=2.5,
                help_text="In microliter (µL), the volume left in the source well. A well with less than this is marked.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="threshold",
            name="dmso",
            field=models.FloatField(
                default=80,
                help_text="In percent. A well with less DMSO than this is marked.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
