# Generated by Django 4.1.7 on 2023-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_harvestprojectmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='harvest_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
