# Generated by Django 4.1.4 on 2022-12-19 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0005_alter_compoundlibrary_options_and_more'),
        ('core', '0019_rename_amount_well_initial_amount_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='from_well',
            new_name='source_wells',
        ),
        migrations.RemoveField(
            model_name='well',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='well',
            name='initial_amount',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='well',
        ),
        migrations.CreateModel(
            name='WellCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='well_compounds', to='compoundlib.compound')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='well_compounds', to='core.well')),
            ],
        ),
        migrations.AddField(
            model_name='well',
            name='compounds',
            field=models.ManyToManyField(blank=True, null=True, through='core.WellCompound', to='compoundlib.compound'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='well_compound',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='withdrawals', to='core.wellcompound'),
            preserve_default=False,
        ),
    ]
