# Generated by Django 4.1.7 on 2023-03-27 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_harvest_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='barcode',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[^\\s]+', 'Plate barcode must not contain strings!')]),
        ),
    ]
