# Generated by Django 4.2.3 on 2026-09-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_unknown_fill_level_after_renamed_library_copies"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
