# Generated by Django 4.1.7 on 2023-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_plate_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodespecification',
            name='number_of_plates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
