# Generated by Django 4.1.4 on 2022-12-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0007_rename_smile_compound_structure'),
        ('core', '0022_rename_well_compound_wellwithdrawal_well'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='compounds',
            field=models.ManyToManyField(through='core.WellCompound', to='compoundlib.compound'),
        ),
    ]
