# Generated by Django 4.1.4 on 2022-12-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_project_name_alter_experiment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='dimension',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.platedimension'),
        ),
    ]
