# Generated by Django 4.1.7 on 2023-03-31 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_measurement_label_alter_measurement_feature_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="measurement",
            unique_together={("well", "label", "measurement_timestamp")},
        ),
    ]
