# Generated by Django 4.1.7 on 2023-03-30 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_measurement_label_alter_measurement_feature_and_more"),
    ]

    def readFromFile(file: str) -> str:
        with open(file, "r") as f:
            return f.read()

    operations = [migrations.RunSQL(readFromFile("./core/db_scripts/perf.sql"))]
