# Generated by Django 4.1.7 on 2023-03-30 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_measurementfeature_abbrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='measurements', to='core.measurementfeature'),
        ),
        migrations.AlterField(
            model_name='measurementfeature',
            name='abbrev',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
