# Generated by Django 4.1.7 on 2023-03-31 13:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_measurement_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatedDetail",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("barcode", models.CharField(max_length=50)),
                ("dimension", models.CharField(max_length=50)),
                ("rows", models.IntegerField()),
                ("cols", models.IntegerField()),
                ("num_wells", models.IntegerField()),
                (
                    "measurement_labels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True), size=None
                    ),
                ),
                ("stats", models.JSONField()),
            ],
            options={
                "db_table": "core_platedetail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WellDetail",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("position", models.IntegerField()),
                ("well_type", models.CharField(max_length=50)),
                ("hr_position", models.TextField()),
                ("plate_id", models.BigIntegerField()),
                ("barcode", models.CharField(max_length=50)),
                ("sample_id", models.BigIntegerField(blank=True, null=True)),
                ("sample", models.CharField(blank=True, max_length=50, null=True)),
                ("initial_amount", models.FloatField(blank=True, null=True)),
                ("withdrawal", models.FloatField(blank=True, null=True)),
                (
                    "measurement_values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(blank=True, null=True), size=None
                    ),
                ),
                (
                    "measurement_labels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=20, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "compounds",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True), size=None
                    ),
                ),
                ("amount", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_welldetail",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="measurementfeature",
            name="abbrev",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
