# Generated by Django 4.1.4 on 2022-12-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compoundlib', '0007_rename_smile_compound_structure'),
        ('core', '0025_alter_plate_dimension'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wellcompound',
            unique_together={('well', 'compound')},
        ),
    ]
