# Generated by Django 4.1.4 on 2022-12-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_wellcompound_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='source_wells',
        ),
        migrations.AddField(
            model_name='wellwithdrawal',
            name='target_well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='source_well_withdrawals', to='core.well'),
        ),
        migrations.DeleteModel(
            name='WellRelation',
        ),
    ]
