# Generated by Django 4.1.7 on 2023-04-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_platedetail_delete_plateddetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platedetail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='welldetail',
            options={},
        ),
    ]
