# Generated by Django 4.1.4 on 2022-12-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_wellwithdrawal_target_well_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellwithdrawal',
            name='target_well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='source_withdrawals', to='core.well'),
        ),
    ]
