# Generated by Django 4.1.7 on 2023-04-03 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_manual_plate_well_mat_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="platedetail",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="welldetail",
            options={"managed": False},
        ),
    ]
