# Generated by Django 4.1.4 on 2023-01-04 14:45

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_measurement_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', core.basemodels.AutoDateTimeField(editable=False)),
                ('from_field', models.CharField(max_length=50)),
                ('to_field', models.CharField(max_length=50)),
                ('amount_field', models.CharField(max_length=50)),
                ('mapping_file', models.FileField(upload_to='')),
                ('source_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_to_plates', to='core.plate')),
                ('target_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_from_plates', to='core.plate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
