# Generated by Django 4.1.4 on 2023-01-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_platemapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platemapping',
            old_name='amount_field',
            new_name='amount_column',
        ),
        migrations.RenameField(
            model_name='platemapping',
            old_name='from_field',
            new_name='from_column',
        ),
        migrations.RenameField(
            model_name='platemapping',
            old_name='to_field',
            new_name='to_column',
        ),
        migrations.AddField(
            model_name='platemapping',
            name='delimiter',
            field=models.CharField(default=';', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platemapping',
            name='quotechar',
            field=models.CharField(default='"', max_length=1),
            preserve_default=False,
        ),
    ]
