# Generated by Django 4.1.4 on 2023-01-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_amount_field_platemapping_amount_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platemapping',
            name='delimiter',
            field=models.CharField(default=',', max_length=1),
        ),
        migrations.AlterField(
            model_name='platemapping',
            name='quotechar',
            field=models.CharField(default='"', max_length=1),
        ),
    ]
