# Generated by Django 4.1.4 on 2023-01-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_platemapping_delimiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='position',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
