# Generated by Django 4.1.4 on 2023-01-05 12:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_plate_experiment_alter_plate_library_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platemapping',
            name='amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.well'),
        ),
        migrations.AlterField(
            model_name='wellcompound',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_compounds', to='core.well'),
        ),
        migrations.AlterField(
            model_name='wellwithdrawal',
            name='target_well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors', to='core.well'),
        ),
        migrations.AlterField(
            model_name='wellwithdrawal',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.well'),
        ),
    ]
