# Generated by Django 4.1.4 on 2023-01-05 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_platemapping_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platemapping',
            name='amount',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
