# Generated by Django 4.1.4 on 2023-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_platemapping_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platemapping',
            name='amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
