# Generated by Django 4.1.4 on 2023-01-05 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_platemapping_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platemapping',
            name='amount',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
