# Generated by Django 4.1.4 on 2023-01-16 09:48

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_platemapping_amount'),
    ]

    def init_well_types(apps, schema_editor):
        call_command('loaddata', 'well_types')

    operations = [
        migrations.CreateModel(
            name='WellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RunPython(init_well_types),
        migrations.AddField(
            model_name='well',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.welltype'),
        ),
    ]
