# Generated by Django 4.1.4 on 2023-01-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_welltype_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('experiment__isnull', True), ('library__isnull', False)), models.Q(
                ('experiment__isnull', False), ('library__isnull', True)), _connector='OR'), name='check_only_library_or_experiment'),
        ),
    ]
