# Generated by Django 4.1.4 on 2023-01-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platetemplate', '0001_initial'),
        ('core', '0046_remove_plate_check_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='platetemplate.platetemplate'),
        ),
    ]
