# Generated by Django 4.1.7 on 2023-02-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_plate_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='measurements', to='core.measurementmetadata'),
        ),
    ]
