# Generated by Django 4.1.7 on 2023-02-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_measurementmetadata_measurement_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_folder_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
