# Generated by Django 4.1.7 on 2023-02-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_experiment_description_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcodespecification',
            options={'ordering': ['id']},
        ),
    ]
