# Generated by Django 4.1.7 on 2023-02-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_project_description_project_project_folder_link'),
        ('core', '0057_plate_unique_barcode_experiment'),
    ]

    operations = [
    ]
